# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Gitlint check
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint-commits:
    name: check-commit-messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitlint Action
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/gitlint
        with:
          pr-number: ${{ github.event.number }}
          base-branch: ${{ github.event.pull_request.base.ref }}